config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :contactos
  devise_for :users
  get 'comunidad', to: 'visitors#comunidad'
  get 'contacto', to: 'visitors#contacto'
  get 'contacto/confirmado', to: 'contactos#confirmado'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "visitors#index"

  #devise_for :users , path_names: {
  #  sign_up: '/ee00442f89b589d2120f4141a415dded'
  #}
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id          :bigint           not null, primary key
#  titulo      :string
#  contenido   :text
#  estado      :string
#  comentarios :text
#  user_id     :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  descripcion :string
#
class Blog < ApplicationRecord
  belongs_to :user
  validates :titulo, presence: true
  validates :contenido, presence: true
  has_one_attached :imagen
  validates :imagen, presence: false, blob: { content_type: :image }

end

app/models/contacto.rb
# == Schema Information
#
# Table name: contactos
#
#  id         :bigint           not null, primary key
#  nombre     :string
#  email      :string
#  telefono   :string
#  mensaje    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Contacto < ApplicationRecord
  validates :nombre, :email, :telefono, :mensaje, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog, only: %i[ show edit update destroy ]
 

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    @blog.estado = "Aprobado"

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:titulo, :contenido, :estado, :comentarios, :user_id, :imagen, :descripcion)
    end
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :confirmado]
  before_action :set_contacto, only: %i[ show edit update destroy ]

  # GET /contactos or /contactos.json
  def index
    @contactos = Contacto.paginate(page: params[:page], per_page: 3)
  end

  def confirmado
  end

  # GET /contactos/1 or /contactos/1.json
  def show
  end

  # GET /contactos/new
  def new
    @contacto = Contacto.new
  end

  # GET /contactos/1/edit
  def edit
  end

  # POST /contactos or /contactos.json
  def create
    @contacto = Contacto.new(contacto_params)

    respond_to do |format|
      if @contacto.save
        format.html { redirect_to "/contacto/confirmado", notice: "Tu información ha sido recibida pronto nos pondremos en contacto contigo." }
        format.json { render :show, status: :created, location: @contacto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactos/1 or /contactos/1.json
  def update
    respond_to do |format|
      if @contacto.update(contacto_params)
        format.html { redirect_to contacto_url(@contacto), notice: "Contacto was successfully updated." }
        format.json { render :show, status: :ok, location: @contacto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1 or /contactos/1.json
  def destroy
    @contacto.destroy

    respond_to do |format|
      format.html { redirect_to contactos_url, notice: "Contacto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacto
      @contacto = Contacto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contacto_params
      params.require(:contacto).permit(:nombre, :email, :telefono, :mensaje)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end

  def comunidad
  end

  def contacto
    @contacto = Contacto.new
    render "contactos/new"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Titulo:</strong>
    <%= blog.titulo %>
  </p>

  <p>
    <strong>Contenido:</strong>
    <%= blog.contenido %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= blog.estado %>
  </p>

  <p>
    <strong>Comentarios:</strong>
    <%= blog.comentarios %>
  </p>

  <p>
    <strong>User:</strong>
    <%= blog.user_id %>
  </p>

</div>

app/views/blogs/_form.html.erb
<!-- Core build with no theme, formatting, non-essential modules -->
 

<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" data-controller="richtext">
    <%= f.input :titulo %>
    <br><br>
    <%= f.input :descripcion %>
     
    <br><br>
    <%= f.input :imagen %>
    <br><br>
    <textarea id="rich-contenido">
      <%= @blog.contenido %>
    </textarea>
    <%= f.input :contenido, as: :hidden  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,  "Registrar" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<link href="https://cdn.jsdelivr.net/npm/suneditor@latest/dist/css/suneditor.min.css" rel="stylesheet">
 
  
<%= stylesheet_link_tag 'blog-form.css' %>

<h1>Modificar blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<%= stylesheet_link_tag 'blog.css' %>


<article class="article-container">
  <% @blogs.each do |blog| %>
  <article class="post" id="<%= blog.id %>">
    <a href="/blogs/<%= blog.id %>">
     
    <%= image_tag url_for(blog.imagen) if blog.imagen.attached? %>
    <%= image_tag("logo.webp") unless blog.imagen.attached? %>

    </a>
    
    <div class="post_body">
        <h2 class="post-title">
          <a href="blogs/<%= blog.id %>" ><%= blog.titulo %></a>

        </h2>
      <p><%= blog.descripcion %></p>
    </div>
  
  </article>
  <% end %>


</article>
<% if user_signed_in? %>
<div style="text-align:center">
  <%= link_to "Nueva Entrada", new_blog_path %>
</div>
<% end %>

app/views/blogs/new.html.erb
<link href="https://cdn.jsdelivr.net/npm/suneditor@latest/dist/css/suneditor.min.css" rel="stylesheet">
 
  
<%= stylesheet_link_tag 'blog-form.css' %>

<h1 style="text-align:center;">Nueva entrada al Blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<%= stylesheet_link_tag 'article.css' %>
<div class="article" style="view-transition-name:full-embed">

  <h1 style="text-align:center"><%= @blog.titulo %></h1>
 
      <%= image_tag url_for(@blog.imagen), style: "width:50%" if @blog.imagen.attached? %>
      <%= image_tag("logo.webp") unless @blog.imagen.attached? %>
      <%= @blog.contenido.html_safe %>

      <hr>
      Registrado el <%= @blog.created_at.strftime("%d/%m/%Y") %> por <b><%= @blog.user.email %></b>
      <% if user_signed_in? && current_user.id == @blog.user_id %>
       | <%= link_to "Modificar Entrada", edit_blog_path(@blog) %> 
      <% end %>
      | <%= link_to "Regresar", blogs_path %>

      <%# button_to "Eliminar Entrada", @blog, method: :delete %>
 
 </div>

<div>
 

app/views/contactos/_contacto.html.erb
<div id="<%= dom_id contacto %>">
  <p>
    <strong>Nombre:</strong>
    <%= contacto.nombre %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contacto.email %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= contacto.telefono %>
  </p>

  <p>
    <strong>Mensaje:</strong>
    <%= contacto.mensaje %>
  </p>

</div>

app/views/contactos/_form.html.erb
<%= simple_form_for(@contacto, wrapper: :custom_form, html: {class: "contact-form"}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

 
    <%= f.input :nombre, wrapper_html: {class: "input-effect"} %>
    <%= f.input :email, wrapper_html: {class: "input-effect"} %>
    <%= f.input :telefono, wrapper_html: {class: "input-effect"} %>
    <%= f.input :mensaje, wrapper_html: {class: "input-effect"} %>
   

    <%# f.button :submit, "Enviar Mensaje", class: "btn-submit" %>
    <button type="submit">enviar mensaje</button>
<% end %>

app/views/contactos/confirmado.html.erb
<%= stylesheet_link_tag 'contact' %>
<section class="contact">
  <%= image_tag "logo.webp", alt: "Contacto", class: "contact-image" %>
</section>

app/views/contactos/edit.html.erb
<h1>Editing contacto</h1>

<%= render "form", contacto: @contacto %>

<br>

<div>
  <%= link_to "Show this contacto", @contacto %> |
  <%= link_to "Back to contactos", contactos_path %>
</div>

app/views/contactos/index.html.erb
<%= stylesheet_link_tag 'datatable' %>

<div class="container-table">
  <h2>Solicitudes de Contacto <small>Mensajes enviados</small></h2>
  <ul class="responsive-table">
    <li class="table-header">
      <div class="col col-1">Fecha</div>
      <div class="col col-2">Nombre</div>
      <div class="col col-3">Email</div>
      <div class="col col-4">Teléfono</div>
    </li>
     <% @contactos.order("id desc").each do |contacto| %>
    <li class="table-row">
      <div class="col col-1" data-label="Fecha"><%= contacto.created_at.strftime("%d/%m/%Y") %></div>
      <div class="col col-2" data-label="Nombre"><%= contacto.nombre %></div>
      <div class="col col-3" data-label="Email"><%= contacto.email %></div>
      <div class="col col-4" data-label="Telefono"><%= contacto.telefono %></div>
     
    </li>

     <li class="table-row" style="background-color: #bfb9b9; " >
          <div class="col col-4" style="color:black" data-label="Mensaje"><%= contacto.mensaje %></div>
     </li>
   
    <% end %>
     
  </ul>

  
  <%= will_paginate @contactos, next_label: "Siguiente", previous_label: "Anterior" %>
</div>

app/views/contactos/new.html.erb
<%= stylesheet_link_tag 'contact' %>

<section class="contact" data-controller="contact">
    <h1 class="title">Contactanos</h1>
    <%= render "/contactos/form", contacto: @contacto %>

    <% if user_signed_in? %>
    <br>
    <br>
    <%= link_to "Ver mensajes", contactos_path %>
    <% end %>
</section>

app/views/contactos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contacto %>

<div>
  <%= link_to "Edit this contacto", edit_contacto_path(@contacto) %> |
  <%= link_to "Back to contactos", contactos_path %>

  <%= button_to "Destroy this contacto", @contacto, method: :delete %>
</div>

app/views/layouts/_flash.html.erb
<section class="container flash">
<% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
          <% if name.to_s == 'notice' %>
          <div class="alert alert-success" role="alert">
            <div class="alert-icon"><i class="flaticon-warning"></i></div>
            <div class="alert-text"><%= msg %></div>
            <!--div class="alert-close">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true"><i class="la la-close"></i></span>
              </button>
            </div -->
          </div>
        <% else %>
          <div class="alert alert-danger xfade xshow" role="alert">
            <div class="alert-icon"><i class="flaticon-questions-circular-button"></i></div>
            <div class="alert-text"><%= msg %></div>
            <!--div class="alert-close">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true"><i class="la la-close"></i></span>
              </button>
            </div-->
          </div>
        <% end %>
      <% end %>
    <% end %>
    <br>
    <br>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Itcscience</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <link rel="shortcut icon" href="<%= asset_path('logo1-icon.svg') %>" type="image/svg+xml">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <%# stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'normalizer' %>
    <%=   stylesheet_link_tag 'layout' %>
    
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

<body >
  <header class="header">
    <nav class="nav" data-controller="index">
      <div class="logo">
      <a href="/"><%= image_tag("logo.webp") %></a>
      
      </div>
      <ul class="nav-menu-complete">
        <li class="nav_element"><a href="/">INICIO</a></li>
        <li class="nav_element"><a href="/blogs">BLOG</a></li>
        <li class="nav_element"><a href="/">NEWSLETTER</a></li>
        <li class="nav_element"><a href="/comunidad">COMUNIDAD</a></li>
        <li class="nav_element"><a href="/contacto">CONTACTO</a></li>
      </ul>

      <div class="btn not-active" id="btn-ham">
        <span class="span"></span>
        <span class="span"></span>
        <span class="span"></span>
      </div>
    </nav>
  </header>

  
  <main class="main">
   <%= render "/layouts/flash"%>
   <%= yield %>
  </main>

  <footer class="footer">
    <p>ITCScience 2023 &copy; -
    <% if user_signed_in? %>
       <%= link_to "Editar perfil", edit_user_registration_path %> -
      <%= link_to "Desconectarse", destroy_user_session_path, data: { "turbo-method": :delete } %>
    <% else %>
      
      <%= link_to "¿Eres administrador?", new_user_session_path %>
    <% end %>
    </p>
  </footer>

 
</body>

</html>

app/views/visitors/comunidad.html.erb
<%= stylesheet_link_tag 'community' %>
<section class="container">
    <h1>Únete a nuestra comunidad</h1>
    <div class="card">
        
        <a class="card-body" href="https://chat.whatsapp.com/EtQk9oMhecp1aFt3akPaOA" _target="blank">
            <%= image_tag("itcs.jpeg") %>
            <p class="card-title">ITCScience</p>
        </a>
        
        <a class="card-body" href="https://chat.whatsapp.com/FTSALNW5qCwK2Yjlszi1Pq" _target="blank">
           
             <%= image_tag("cien.webp") %>
            <p class="card-title">Ciencias👾Computacionales</p>
        </a>
        
        <a class="card-body" href="https://chat.whatsapp.com/Gqcit7OCPiiIoZp93wjNjF" _target="blank">
                        <%= image_tag("pog.webp") %>
            <p class="card-title">👾 Programadores 🖥️</p>
        </a>
        
        <a class="card-body" href="https://chat.whatsapp.com/ER1SMqM6GmZKGBIWD7JUEs" _target="blank">
            <%= image_tag("recur.webp") %>
            <p class="card-title">📚 Recursos Informatica 🤓</p>
        </a>
        
    </div>
</section>

app/views/visitors/index.html.erb
<%= stylesheet_link_tag 'inicio' %>

<div class="index">
  <div class="main_index">
    <div class="wrapper-img">
      <%= image_tag("logo1-icon.svg",  class: "img-1") %>
    </div>
    <blockquote class="quote">
     <q>El mayor enemigo del conocimiento no es la ignorancia, sino la ilusión del conocimiento</q>
    <footer>- Stephen Hawking</footer>
    </blockquote>

    <a  href="#info" ><button class="btn-more">Saber mas 
    <%= image_tag("down-arrow.svg",  class: "btn-img") %>
    </button>
    </a>
    </div>
    <div id="info" class="info">
    
    <%= image_tag("circuito.svg", class: "img-2") %>
    
    <div class="info_text">
      <span>Acerca de</span>
      <h3>Que es ITCScience?</h3>
      <p>La Comunidad ITCScience es una comunidad de ciencia y tecnología, creada con la finalidad de difundir las Ciencias Computacionales e Informática en general.
      </p>
      </div>
    </div>
    <div class="groups">
  <div class="groups_info">
 <span>Comunidad</span>
    <h3>Nuestros <span>Grupos</span> </h3>
   <p>Tenemos diversos grupos con temáticas en especifico para colaborar,aportar,aplicar,aprender y debatir entre los miembros de la comunidad</p>
  </div>
  <div class="groups_container">
 <div class="group_what">
  <div class="circle"></div>
     <%= image_tag("cien.webp", loading: "lazy") %>
 
   <div>
    <h4>ciencias Computacionales</h4>
    <p>Este grupo se centra en las Ciencias Computacionales,donde se Realizan diversas aclaraciones y debates donde se comparte el conocimiento del area </p>
  <a href="https://chat.whatsapp.com/FTSALNW5qCwK2Yjlszi1Pq">ingresar al grupo
     <%= image_tag("enter-outline.svg", class: "img_wh") %>

  </a> 
   </div>
 </div>
 <div class="group_what">
  <div class="circle"></div>
  <%= image_tag("pog.webp", loading: "lazy") %>
  
  <div>
   <h4>Programadores</h4>
   <p>Este grupo se basa en tema mas general en el area informática,donde se ayudan a resolver problemas de código y se resulten dudas mas simples</p>
 <a href="https://chat.whatsapp.com/Gqcit7OCPiiIoZp93wjNjF">ingresar al grupo
      <%= image_tag("enter-outline.svg", class: "img_wh") %>
 </a> 
  </div>
</div>
<div class="group_what">
  <div class="circle"></div>
   <%= image_tag("recur.webp", loading: "lazy") %>
  <div>
   <h4>Recursos Informática</h4>
   <p>Grupo destinado a compartir recursos de informática,donde ademas se permite también recursos de matemáticas y electronica </p>
 <a href="https://chat.whatsapp.com/ER1SMqM6GmZKGBIWD7JUEs">ingresar al grupo
    <%= image_tag("enter-outline.svg", class: "img_wh") %>
  </a> 
 </div>
</div>
<div class="group_what">
  <div class="circle"></div>
   <%= image_tag("itcs.jpeg", loading: "lazy") %>
  <div>
    <h4>ITCScience</h4>
    <p>grupo de avisos y difusión de la comunidad</p>
 <a href="https://chat.whatsapp.com/EtQk9oMhecp1aFt3akPaOA">Ingresar al grupo  
   <%= image_tag("enter-outline.svg", class: "img_wh") %>
 </a>
  </div>
</div>
  </div>
    </div>
</div>